datasources:
  default:
    connection: 
      url: mongodb://192.168.0.21/dzgy
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
plugins:
  - "@steedos/app-contracts"
  - "@steedos/steedos-plugin-workflow"